name: Eugenio Wilman
favicon: null
layout_spectrum: 1
typography_spectrum: 0.18552
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#212121'
    - '#858583'
    - '#424242'
    - '#d9d9d7'
  brandStrength: 0.6875
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
