name: EmotionWorks
favicon: null
layout_spectrum: 0.95956
typography_spectrum: 0.19839
title: 'Corporate Photography & Video production'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ef9233'
    - '#565857'
    - '#8a8e91'
    - '#af6629'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
